### ISSUE TITLE
Questionable accuracy of package:upgradeable output

### ISSUE THREAD

**Issue by pixelchutes** [meltingmedia/MODX-Shell#11]
Running `modx package:upgradeable` on a site provides the following result:

> - Ace
> - DBAPI
> - FormIt
> - Login

However, according to Package Management (Extras > Installer) in MODX Manager, all Extras show as currently up-to-date. It seems this may be incorrect or incompatible? _(Testing against 2.3.4-dev builds)_

Also, in one occasion, I was seeing duplicates in the output from `package:upgradeable` ...it may be helpful if the current / new version could be displayed to better understand what may be happening.

**Comment by rtripault** [comment]
Hey Mike, would you mind testing if 98b3bebcaf79e53a3a89714208f6fcd51da471e2 resolves the issue ?
Thanks

**Comment by pixelchutes** [comment]
Bingo!

**Comment by pixelchutes** [comment]
Would it be possible to return the current and/or at least new version available to upgrade to?

**Comment by rtripault** [comment]
Late reply (still had this in my inbox!).

It should be possible. You could probably try to read the XML response here https://github.com/meltingmedia/MODX-Shell/blob/master/src/Command/Package/Upgradeable.php#L89 and find the latest version, then return that version instead of a boolean.

Could be a nice addition!
